providers = ["node", "python"]

[variables]
NODE_ENV = 'production'

[deploy]
startCommand = "cd client && npm install && npm run build && cd .. && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn drf_api.wsgi"